[x,Fs]=audioread('acoustic.wav');
sound(x,Fs);
dt=1/Fs;
t=0:dt:(lenght(x)*dt)-dt;
plot(t,x);
xlabel('Tiempo');
ylabel('Amplitud');
title('Senal original');
figure;
frecuencia=(Fs/2)/1000;
disp("Frecuencia maxima es" + frecuencia);
Energia= sum(x.^2);
Potencia= (1/((lenght(x)-1)+1)).*Energia;
disp("Enegia  es" + Energia);
disp("Potencia media es" + potencia);
pause(20);